#!/bin/bash

rm -r Course_0*
git init
git remote add origin https://github.com/gperdrizet/fullstack.git
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt install -y git-lfs
git lfs install
git config credential.helper cache
git pull origin main